@extends('layouts/template')

@section('contents')
<!-- Container for the entire page content -->
<div class="bg-white rounded-xl shadow-sm p-4">
    <!-- Breadcrumb Navigation -->
    <nav class="text-sm mb-4" aria-label="Breadcrumb">
        <ol class="list-reset flex text-gray-600">
            <li><a href="{{ $_ENV['APP_ENV'] }}/dashboard" class="text-blue-600 hover:text-blue-800">Dashboard</a></li>
            <li><span class="mx-2">/</span></li>
            <li><a href="{{ $_ENV['APP_ENV'] }}/partshortage" class="text-blue-600 hover:text-blue-800">Part Shortage</a></li>
            <li><span class="mx-2">/</span></li>
            <li class="text-gray-500">Bulk Part Shortage Report</li>
        </ol>
    </nav>
<!-- Responsive Header Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-4 items-start bg-white p-4 rounded-xl shadow-sm border border-slate-200">
        <!-- Left Section -->
        <div class="col-span-1 lg:col-span-2">
            <h1 class="header-title uppercase tracking-wider underline decoration-red-600 decoration-4 underline-offset-4 mb-3">Bulk part shortage Report</h1>
            <div id="topic-bm" class="text-blue-700 font-bold text-lg mb-4 bg-blue-50 inline-block px-3 py-1 rounded-md border border-blue-100">
                Data B/M : MMX/YY (YYYYMMDD)
            </div>
            
            <div class="flex flex-col sm:flex-row sm:items-center gap-4 mb-2">
                <span class="font-bold text-slate-700 bg-slate-100 px-3 py-1 rounded">(1). Bulk Part shortage</span>
                <div class="flex items-center gap-2">
                    <!--<div class="bg-yellow-300 px-4 py-1 border border-yellow-500 rounded text-sm shadow-inner font-mono">xxxxxx</div>
                    <div class="bg-yellow-300 px-3 py-1 border border-yellow-500 rounded text-sm font-bold shadow-inner">S</div>--->
                    <!--<span class="text-red-600 font-bold ml-2 animate-pulse flex items-center gap-1">
                        <i class="fas fa-exclamation-triangle"></i> Serious shortage
                    </span>--->
                </div>
            </div>
        </div>
        
        <!-- Right Section -->
        <div class="col-span-1 flex flex-col items-start md:items-end w-full">
            <div class=" hidden bg-slate-50 border border-slate-300 p-3 rounded-lg text-xs text-left shadow-sm w-full md:w-auto">
                <div class="font-bold mb-2 text-slate-700 border-b border-slate-200 pb-1"><i class="fas fa-info-circle mr-1"></i> Type of reason</div>
                <ul class="space-y-1 text-slate-600">
                    <li><span class="font-bold">A</span> = Usage volume increasing</li>
                    <li><span class="font-bold">B</span> = Vendor delay</li>
                    <li><span class="font-bold">C</span> = Other reason (detail in remark)</li>
                </ul>
            </div>
            <div class="mt-4 text-blue-700 font-semibold bg-blue-50 px-4 py-2 rounded-lg border border-blue-100 flex items-center gap-2">
                <i class="far fa-calendar-alt"></i> Date : {{ date('d-M-Y') }}
            </div>
        </div>
    </div>

    <!-- Table Container -->
        <table id="shortageTable" class="display nowrap w-full text-sm">
            {{-- Table header will be dynamically generated by DataTables --}}
            <tbody>
            </tbody>
        </table>

    <!-- Toast Notification -->
    <div id="toast" class="fixed top-5 right-5 transform -translate-y-20 opacity-0 transition-all duration-300 z-50 pointer-events-none">
        <div class="bg-white border-l-4 border-green-500 text-slate-700 px-6 py-4 rounded shadow-xl flex items-center gap-3 font-semibold">
            <i class="fas fa-check-circle text-green-500 text-xl"></i>
            <span id="toast-message">Data saved successfully</span>
        </div>
    </div>

    <!-- Loading Overlay -->
    <div id="loadingOverlay" class="fixed inset-0 bg-gray-800 bg-opacity-50 z-[9999] flex flex-col justify-center items-center hidden">
        <!-- Spinner -->
        <div class="animate-spin rounded-full h-16 w-16 border-t-4 border-b-4 border-white mb-4"></div>
        <!-- ข้อความ -->
        <h2 class="text-white text-xl font-semibold">กำลังโหลดข้อมูล กรุณารอสักครู่...</h2>
    </div>
</div><!-- End of Container -->
@endsection

@section('scripts')
    {{-- เรียกใช้ไฟล์ที่ Rspack bundle ออกมาแล้ว --}}
    <script src="{{ $_ENV['APP_JS'] }}/partshortage.js?ver={{ $GLOBALS['version'] }}"></script>
@endsection