-- 1. ตาราง Master สำหรับหมวดหมู่
CREATE TABLE CATEGORIES (
    CATEGORY_ID         INT AUTO_INCREMENT PRIMARY KEY,
    PARENT_CATEGORY_ID  INT NULL, 
    CATEGORY_CODE       VARCHAR(50) UNIQUE NOT NULL,
    CATEGORY_NAME       VARCHAR(255) NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_CATEGORY_ID) 
        REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE SET NULL
);

-- 2. ตาราง Master สำหรับคุณสมบัติ (Attribute Master)
CREATE TABLE ATTRIBUTES_MASTER (
    ATTRIBUTE_ID    INT AUTO_INCREMENT PRIMARY KEY,
    ATTRIBUTE_CODE  VARCHAR(50) UNIQUE NOT NULL, -- เช่น 'ram_gb', 'color'
    ATTRIBUTE_LABEL VARCHAR(255) NOT NULL,      -- เช่น 'RAM (GB)', 'สี'
    DATA_TYPE       VARCHAR(20) DEFAULT 'string', -- string, number, boolean
    UNIT            VARCHAR(20) NULL             -- เช่น 'GB', 'Watt', 'Inch'
);

-- 3. ตารางเชื่อมโยงหมวดหมู่และคุณสมบัติ (Category-Attribute Mapping)
CREATE TABLE CATEGORY_ATTRIBUTES (
    CATEGORY_ID  INT NOT NULL,
    ATTRIBUTE_ID INT NOT NULL,
    PRIMARY KEY (CATEGORY_ID, ATTRIBUTE_ID),
    CONSTRAINT FK_CA_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_CA_ATTRIBUTE FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTES_MASTER(ATTRIBUTE_ID)
);

-- 4. ตารางสินค้า
CREATE TABLE PRODUCTS (
    PRODUCT_ID      VARCHAR(36) PRIMARY KEY,
    CATEGORY_ID     INT NOT NULL,
    SKU             VARCHAR(50) UNIQUE NOT NULL,
    NAME            VARCHAR(255) NOT NULL,
    BASE_PRICE      DECIMAL(12, 2) NOT NULL,
    -- เก็บข้อมูลจริงเป็น JSON โดยอ้างอิง Key จาก ATTRIBUTES_MASTER.ATTRIBUTE_CODE
    CATEGORY_SPECS  JSON NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE PRICE_HISTORY (
    PRICE_ID        INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID      VARCHAR(36) NOT NULL,
    OLD_PRICE       DECIMAL(12, 2),
    NEW_PRICE       DECIMAL(12, 2) NOT NULL,
    CHANGE_REASON   VARCHAR(255), -- เหตุผลการเปลี่ยนราคา เช่น 'โปรโมชั่น', 'ปรับตามต้นทุน'
    CHANGED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PRICE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
);

ALTER TABLE PRODUCTS ADD COLUMN IS_STOCK_MANAGED BOOLEAN DEFAULT FALSE;

CREATE TABLE STOCK (
    PRODUCT_ID      VARCHAR(36) PRIMARY KEY,
    QUANTITY        INT DEFAULT 0,
    MIN_THRESHOLD   INT DEFAULT 0, -- จุดแจ้งเตือนเมื่อสินค้าใกล้หมด
    LOCATION        VARCHAR(100),   -- ที่เก็บสินค้า เช่น 'A1-02'
    LAST_UPDATED    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_STOCK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
);

-- 3. ตารางเก็บประวัติการเบิก-จ่าย (Transactions)
CREATE TABLE STOCK_TRANSACTIONS (
    TRANSACTION_ID  INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID      VARCHAR(36) NOT NULL,
    TRAN_TYPE       ENUM('IN', 'OUT', 'ADJUST') NOT NULL, -- รับเข้า, เบิกออก, ปรับปรุงสต็อก
    QUANTITY        INT NOT NULL,
    REF_NO          VARCHAR(50), -- เลขที่เอกสารอ้างอิง เช่น เลขใบเบิก หรือ PO
    REMARKS         VARCHAR(255),
    CREATED_BY      VARCHAR(100),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TRAN_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
);
