-- Oracle schema: inventory movement, lot tracking, and balances

--warehouses

CREATE TABLE warehouses (
    WHID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    WHcode VARCHAR2(50) NOT NULL UNIQUE,       -- รหัสคลังสินค้า เช่น 'WH-MAIN', 'WH-MFG'
    WHname VARCHAR2(150) NOT NULL,             -- ชื่อคลังสินค้า เช่น 'Main Warehouse'
    WHOWNER VARCHAR2(6),
    location VARCHAR2(1024) NULL,                     -- รายละเอียดสถานที่ตั้ง
    is_active BOOLEAN DEFAULT TRUE,         -- เปิด/ปิด การใช้งานคลังสินค้านี้
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE product_lots (
    lot_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    lot_number VARCHAR2(100) NOT NULL,
    mfg_date DATE,
    expiry_date DATE,
    received_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_lot_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT uq_lot_product_number UNIQUE (product_id, lot_number),
    CONSTRAINT ck_product_lots_is_active CHECK (is_active IN (0, 1))
);




CREATE TABLE stock_movements (
    movement_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    document_no VARCHAR2(50) NOT NULL UNIQUE,
    movement_type VARCHAR2(20) NOT NULL,
    source_storage NUMBER,
    dest_storage NUMBER,
    status VARCHAR2(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_mov_source_wh FOREIGN KEY (source_storage) REFERENCES warehouses(WHID),
    CONSTRAINT fk_mov_dest_wh FOREIGN KEY (dest_storage) REFERENCES warehouses(WHID)
);


-- รายการสินค้าในเอกสาร (ระบุ Lot)
CREATE TABLE stock_movement_items (
    item_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    movement_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    lot_id NUMBER,
    quantity NUMBER(12, 4) NOT NULL,
    unit_cost NUMBER(15, 2),
    remark CLOB,
    CONSTRAINT fk_item_movement FOREIGN KEY (movement_id) REFERENCES stock_movements(movement_id) ON DELETE CASCADE,
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_item_lot FOREIGN KEY (lot_id) REFERENCES product_lots(lot_id)
);

CREATE TABLE inventory_balances (
    balance_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    warehouse_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    lot_id NUMBER,
    quantity NUMBER(12, 4) DEFAULT 0.0000,
    reserved_quantity NUMBER(12, 4) DEFAULT 0.0000,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_balance_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(warehouse_id),
    CONSTRAINT fk_balance_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_balance_lot FOREIGN KEY (lot_id) REFERENCES product_lots(lot_id),
    CONSTRAINT uq_balance_wh_prod_lot UNIQUE (warehouse_id, product_id, lot_id)
);

-- Oracle ไม่มี ON UPDATE CURRENT_TIMESTAMP จึงใช้ trigger แทน
CREATE OR REPLACE TRIGGER trg_inventory_balances_upd
BEFORE UPDATE ON inventory_balances
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE INDEX idx_balance_lookup ON inventory_balances(warehouse_id, product_id, quantity);
CREATE INDEX idx_lots_expiry ON product_lots(expiry_date);
CREATE INDEX idx_lots_received ON product_lots(received_date);